export const env = {
  LOCAL_DEV_APP_HOST: 'localhost',
  LOCAL_DEV_APP_PORT: 8017,
  MOCK_DATABASE: {
    USER: {
      ID: '2112762',
      EMAIL: 'd@gmail.com',
      PASSWORD: '123456',
    },
  },
  ACCESS_TOKEN_SECRET_SIGNATURE: 'ACCESS_TOKEN_SECRET_SIGNATURE',
  REFRESH_TOKEN_SECRET_SIGNATURE: 'REFRESH_TOKEN_SECRET_SIGNATURE',
}
